version: '3.7'
services:
  api:
    build:
       context: .
       dockerfile: Dockerfile
    ports:
      - 8001:80
  nginx:
    stdin_open: true
    tty: true
    restart: 'always'
    links: 
      - api
    build:
      context: .
      dockerfile: nginx/Dockerfile
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf 
    ports:
      - 8015:80   

